#!/usr/bin/env python3
#
# TODO: Merge all responses into one in a syntactically correct way.

import os
import sys
import xml.dom.minidom
import yaml

from xml.etree import ElementTree

from rauth import OAuth1Service

PAGE_SIZE=5

def print_xml(string):
    xmlval = xml.dom.minidom.parseString(string)
    pretty_xml_as_string = xmlval.toprettyxml()
    sys.stdout.buffer.write(pretty_xml_as_string.encode('utf-8'))

with open("creds.yml", 'r') as creds_stream:
    creds = yaml.load(creds_stream)
    consumer_key = creds['consumer_key']
    consumer_secret = creds['consumer_secret']

if os.path.exists('permcreds.yml'):
    with open("permcreds.yml", 'r') as permcreds_stream:
        permcreds = yaml.load(permcreds_stream)
        access_token = permcreds['authorized_token']
        access_token_secret = permcreds['authorized_token_secret']
else:
    access_token = ''

tripit = OAuth1Service(
    name='tripit',
    consumer_key=consumer_key,
    consumer_secret=consumer_secret,
    request_token_url='https://api.tripit.com/oauth/request_token',
    access_token_url='https://api.tripit.com/oauth/access_token',
    authorize_url='https://www.tripit.com/oauth/authorize',
    base_url='https://api.tripit.com/v1/')

if not access_token:
    request_token, request_token_secret = tripit.get_request_token()

    authorize_url = tripit.get_authorize_url(request_token, oauth_callback="http://localhost:8080/")

    print('Visit this URL in your browser: ' + authorize_url)
    pin = input('Press Return to continue')

    session = tripit.get_auth_session(request_token,
                                      request_token_secret)

    access_token = session.access_token
    access_token_secret = session.access_token_secret

    data = dict(
        authorized_token = access_token,
        authorized_token_secret = access_token_secret
    )

    print(yaml.dump(data, default_flow_style=False))
else:
    tripit = OAuth1Service(
        name='tripit',
        consumer_key=consumer_key,
        consumer_secret=consumer_secret,
        request_token_url='https://api.tripit.com/oauth/request_token',
        access_token_url='https://api.tripit.com/oauth/access_token',
        authorize_url='https://www.tripit.com/oauth/authorize',
        base_url='https://api.tripit.com/v1/')

    session = tripit.get_session((access_token, access_token_secret))

    r = session.get('https://api.tripit.com/v1/list/trip/traveler/all/past/true/include_objects/true/page_size/' + str(PAGE_SIZE))

    root = ElementTree.fromstring(r.content)

    max_page = int(root.find('max_page').text)

    for page in range(1, max_page):
        r = session.get('https://api.tripit.com/v1/list/trip/traveler/all/past/true/include_objects/true/page_num/' + str(page))
        print_xml(r.content)
